#!/usr/bin/env bash
#This script displays hours from 0 to 12
#displays minutes from 1 to 59
h=0
m=1
while [ $h -le 12 ]; do
echo "Hour: ${h}"
 while [ $m -lt 60 ]; do
echo $m
 (( m+=1 ))
done
  (( m=1 ))
  (( h+=1 ))
done
